# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME', vendor]


# Site Settings
title: "Build IT Right 2018"
email: "bitrconference@gmail.com"
description: "Build IT Right is a conference for people interested in
IT based in Newcastle Upon Tyne"
baseurl: ""
url: "https://bitr.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-122482205-1"
googleAnalyticsSiteUrl: "bitrconf.org"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "Fiona Hobbs"
organizerAlternateName: "Chris Howe-Jones"
organizerDescription: "Software Developers, Agile/Lean coaches with a
strong interest in promoting software development in the North East of
England."
organizerEmail: "bitrconference@gmail.com"
organizerLogo: "/img/seo/beaconhouse-logo.png"
organizerLink: "http://www.beaconhouse-events.co.uk/"

# Head
metaKeywords: "event, bitr, BuildITRight, software, programming,
agile, lean, developers, newcastle, tyne and wear, north east england"
twitterAccount: "@bitr"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "http://bit.ly/2NzkBtb"
c4sponsorsUrl: "/assets/BITR_Sponsorship_Pack.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Logistics"}
 - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 - {permalink: "/#tickets", text: "Buy tickets"}
 - {link: "/assets/BITR_Sponsorship_Pack.pdf", text: "Become a sponsor"}
 - {link: "http://bit.ly/2NzkBtb", text: "Become a speaker"}
rightNavigationButtons:
 - {permalink: "/#tickets", text: "Buy tickets"}
 - {link: "/assets/BITR_Sponsorship_Pack.pdf", text: "Become a sponsor"}
 - {link: "http://bit.ly/2NzkBtb", text: "Become a speaker"}

# Hero Block
heroImage: "newcastle-bridges.jpg"
heroTitle: "Build IT Right <typeout> 2018"
eventDate: "21st November, 2018"
#typeoutTextValues: '"Newcastle Upon Tyne", "UK"'
typeoutFallback: "Newcastle Upon Tyne"
heroButtons:
 - {permalink: "/#tickets", text: "Buy tickets"}
 - {link: "assets/BITR_Sponsorship_Pack.pdf", text: "Become a sponsor"}
 - {link: "http://bit.ly/2NzkBtb", text: "Become a speaker"}

# About Block
aboutTitle: "About Build IT Right"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "An IT conference in the North East of England that focuses on
 how to build software with latest tools, languages and approaches! Awesome speakers and lots of fun!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "300", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "15", specialCharacter: "+", info: "hours", detail: "of discussions on effective software development"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from UK and beyond"}
 - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus the most interesting 'water cooler' talk outside the talks"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 2
rockstarSpeakersTitle: "World class speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Crowne Plaza Hotel, Newcastle Upon Tyne"
eventLocationLink: "http://bit.ly/2L1b78j"
eventStreetAddress: "Hawthorn Square, Forth Street"
eventAddressLocality: "Newcastle Upon Tyne"
eventAddressLocalityRegion: "Tyne and Wear"
eventPostalCode: "NE1 3SA"
eventAddressCountry: "United Kingdom"
eventStartTime: "2018-11-21T09:30"
eventDoorTime: "08:30"
eventEndTime: "2018-11-21T19:00"
eventPlaceCoordinates: "54.967145, -1.616574"
mapCenterCoordinates: "54.967145, -1.616574"
mapMobileCenterCoordinates: "54.967145, -1.616574"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Crowne Plaza Hotel"
venueFeatures: ["Spa and fitness suite", "WIFI in all rooms and public areas", "Located in the Stephenson Quarter in the city center"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "bitrconf"
twitterFeed: "http://twitter.com/bitrconf"

# Partners Block
organizersTitle: "Organisers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://github.us18.list-manage.com/subscribe/post?u=440fd2edca6e5128f8dd511bf&amp;id=883fca8761"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricing"
ticketsInfo: "Tickets grant access to all conference sections, coffee breaks, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Standard"
  price: "£150"
  priceCurrency: "+ VAT"
  ticketsNumber: "200"
  ribbon: "Full price"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Access to all talks", "After drinks reception", "Online video access"]
  validFrom: "2018-09-01T00:00"
  validThrough: "2018-11-20T23:59"
  disabled: true
 -
  name: "Early Bird"
  price: "£99"
  priceCurrency: "+ VAT"
  ticketsNumber: "50"
  ribbon: "-33%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Access to all talks", "After drinks reception", "Online video access"]
  validFrom: "2018-07-10T10:00"
  validThrough: "2018-08-31T23:59"
 -
  name: "Concessionary"
  price: "£99"
  priceCurrency: "+ VAT"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Students require a valid student email address at time of purchase."
  ticketContentList: ["Access to all talks", "After drinks reception", "Online video access"]
  validFrom: "2018-07-10T10:00"
  validThrough: "2018-11-20T23:59"
  #soldOut: true
  #soldOutText: "Sold Out"

# Footer
socialLinks:
 #- {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://twitter.com/bitrconf", icon: "twitter"}
 #- {link: "https://facebook.com/GDGLviv", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.beaconhouse-events.co.uk", text: "Beacon House Events"}
   - {link: "https://www.ihg.com/crowneplaza/hotels/gb/en/newcastle-upon-tyne/nclsq/hoteldetail", text: "Crowne Plaza Newcastle"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:bitrconference@gmail.com", text: "bitrconference@gmail.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "bitrconf"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "The North East of England and Newcastle Upon Tyne in
particular has a long tradition of software development. This
conference is intended to showcase the best talent in the region while
challenging established precedent in how software is built."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "54.967145, -1.616574"
logisticsMapMobileCenterCoordinates: "54.967145, -1.616574"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Newcastle"
directionDetailsCards:
 - {title: "From the Airport", information: 'Newcastle International Airport is situated to the west of the city. It is easily reachable by car, public transport or taxi. More information is available at the <a href="https://www.newcastleairport.com/getting-here">airport website</a>.'}
 - {title: "Public Transit", information: 'Newcastle is well served by public transport including local bus routes and the metro train transit system. See the
 <a href="https://www.nexus.org.uk/">Nexus website</a> for more details.'}
 - {title: "Hotels", information: 'Newcastle has lots of great hotels and hostels. More information can be found in the questions section below.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "http://bit.ly/2L1b78j", text: "Crowne Plaza Newcastle"}
     - {link: "https://www.jurysinns.com/hotels/newcastle/newcastle", text: "Jurys Inn Newcastle"}
     - {link: "https://www.travelodge.co.uk/hotels/633/Newcastle-Quayside-hotel", text: "Travelodge Newcstle Quayside"}
     - {link: "http://www.sleeperz.com/newcastle", text: "Sleeperz Newcastle"}
     - {link: "https://www.ihg.com/holidayinnexpress/hotels/gb/en/newcastle-upon-tyne/ncljb/hoteldetail", text: "Holiday Inn Express Newcastle City Centre"}
   -
    title: "Registration"
    links:
     - {link: "http://bit.ly/2L1b78j", text: "Crowne Plaza Newcastle"}
   -
    title: "Attendance Details"
    links:
     - {link: "http://bit.ly/2L1b78j", text: "Crowne Plaza Newcastle"}

# Hackathon
hackathonTitle: "Hack-NE-thing"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Alexa Skills Kit Challenge", image: "echo-dot.jpg", details: "Help out a charity by building an app using the Alexa Skills Kit. Come up with an
 idea for how to contribute to local North East charities using Alexa. Build something in a lunchtime.&nbsp;<a href
 ='https://developer.amazon.com/alexa-skills-kit'>Alexa Skills Kit</a>"}
 - {title: "Mobile App Challenge", image: "iphone.jpg", details: "Help out a charity by building a mobile app using whatever technology you fancy. Come up with an
 idea for how to contribute to local North East charities. Assemble a team of fellow attendees with a mix of UX, development
 and testing skills and see what you can build in an hour or so."}
 - {title: "Come up with your own idea", image: "question-mark.jpg", details: "Help out a charity by building whatever you like using whatever technology you fancy. Come up with an
 idea for how to contribute to local North East charities. Assemble a team of fellow attendees with a mix of UX, development
 and testing skills and see what you can build in an hour or so."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "Watch this space!", image: "echo-dot.jpg", info: "Watch this space for announcements on prizes."}
 # - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 # - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 # - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Crowne Plaza Newcastle"
hackathonLocationLink: "http://bit.ly/2L1b78j"
hackathonStreetAddress: "Hawthorn Square, Forth Street"
hackathonAddressLocality: "Newcastle Upon Tyne"
hackathonAddressLocalityRegion: "Tyne and Wear"
hackathonPostalCode: "NE1 3SA"
hackathonAddressCountry: "United Kingdom"
hackathonTimeTitle: "Hack-NE-thing"
hackathonStartTime: "2018-11-21T12:30"
hackathonDoorTime: "09:00"
hackathonEndTime: "2018-11-21T14:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "54.967145, -1.616574"
hackathonMapCenterCoordinates: "54.967145, -1.616574"
hackathonMapMobileCenterCoordinates: "54.967145, -1.616574"
